name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write   # Required for GitHub annotations
      pull-requests: write

    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      # Step 4: Run Pylint and generate annotations
      - name: Run Pylint
        run: |
          pylint --output-format=json . | tee pylint-report.json
        continue-on-error: true

      # Step 5: Convert Pylint JSON to GitHub Annotations
      - name: Annotate Lint Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          eslint-json: pylint-report.json
        continue-on-error: true

      # Step 6: Run tests
      - name: Run tests
        run: pytest
